# Lines added by author
	if (IFW_FSM_STATE_UPDATE(IFW_BLE_LL_STANDBY_STATE, LL_STATE, CORE)) {
		IFW_DEBUG_LOG_UPDATE_ERROR();
		return;
	}
	IFW_DEBUG_LOG_UPDATE_SUCCESS(
		"state: IFW_BLE_LL_STANDBY_STATE, type: LL_STATE, index: CORE.");
		if (IFW_FSM_STATE_UPDATE(IFW_BLE_LL_CONNECTION_STATE, BLE_STATE,
					 CORE)) {
			IFW_DEBUG_LOG_UPDATE_ERROR();
			return;
		}
			if (IFW_FSM_STATE_UPDATE(IFW_BLE_LL_CONNECTION_STATE,
						 LL_STATE, CORE)) {
				IFW_DEBUG_LOG_UPDATE_ERROR();
				return err;
			}
			IFW_DEBUG_LOG_UPDATE_SUCCESS(
				"IFW_BLE_LL_CONNECTION_STATE, LL_STATE, CORE.");
